[package]
name = "example"
version = "0.1.0"
authors = ["Jarrett Helton <jaydhelton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lugnut = { path = "../" }
