[package]
name = "lugnut"
version = "0.0.1"
license = "MIT"
description = "Coming Soon"
homepage = "https://github.com/JayHelton/lugnut"
documentation = "https://github.com/JayHelton/lugnut"
readme = "README.md"
authors = ["jayhelton <jaydhelton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
