[package]
name = "lugnut"
version = "0.0.1"
license = "MIT"
description = "Coming Soon"
homepage = "https://github.com/JayHelton/lugnut"
documentation = "https://github.com/JayHelton/lugnut"
readme = "README.md"
authors = ["jayhelton <jaydhelton@gmail.com>", "kevinburchfield <kevinburchfi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
url = "2.2.1"
data-encoding = "2.3.2"
thiserror = "1.0"
hmac = "0.10.1"
sha-1 = "0.9"
sha2 = "0.9"
sha3 = "0.9"

[dependencies.crypto-mac]
version = "0.10"
features = ["std"]
