[package]
name = "lugnut"
version = "0.0.1"
authors = ["jayhelton <jarrett.helton@auth0.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
